### ISSUE TITLE
Putty: unknown option -tt

### ISSUE THREAD

**Issue by rakk7** [danilopolani/vscode-yet-another-phpunit#1]
Great work, I like it.

I am using Windows 10, and using ( Laravel Homestead ) vagrant box as a guest.

Whenever I try to do the test via SSH mode, I get this error by Putty:
```unknown option -tt```

---

```json
"yet-phpunit.ssh.enable": true,
"yet-phpunit.ssh.binary": "c:/Users/user11/tools/putty.exe -ssh",
"yet-phpunit.ssh.host": "127.0.0.1",
"yet-phpunit.ssh.user": "vagrant",
"yet-phpunit.ssh.port": "2222",
"yet-phpunit.ssh.options": null,
"yet-phpunit.ssh.paths": {
  "d:/sites/blog": "/home/vagrant/code/blog"
},
```

**Comment by danilopolani** [comment]
Hello, thank you for your feedback! I'll look into it tomorrow and let you know :)

**Comment by danilopolani** [comment]
Hello @rakk7, sorry for the delay, I had a full weekend. I pushed to the Marketplace a new version, please try to update the extension and try again, it should be fixed now.

Let me know!

**Comment by rakk7** [comment]
@danilopolani Thank you, works great. Love it

-- -
Maybe I should put this in another issue?

When I run the tests.. It doesn't run it in "git bash", yet the default windows's terminal ( CMD ) is opened instead, not the "git bash".

Which means coloring from phpunit.xml file doesn't take effect.

![2019-04-29 220331](https://user-images.githubusercontent.com/46261343/56919992-b25eb500-6aca-11e9-87c6-2838329bb0b8.png)

**Comment by danilopolani** [comment]
Happy that it works! About the terminal yes, is better to create another issue so we can close this one, I need to do some researches about how to choose which "terminal" to use for a VSCode task, I'll let you updated in the other issue.

Thanks!
