### ISSUE TITLE
Could not open input file: /home/ . . . /vendor/bin/phpunit

### ISSUE THREAD

**Issue by joelpiccoli** [danilopolani/vscode-yet-another-phpunit#10]
Hello everyone! I'm facing an issue that I can not run any kind of test because I get this error:

```
> Executing task: /home/ . . . /vendor/bin/phpunit /home/ . . . /Tests/Feature/ . . . /ControllerIndexTest.php --filter '^.*::it_fails_to_access_the_endpoint_if_the_user_is_not_authenticated( .*)?$'  <

Could not open input file: /home/ . . . /vendor/bin/phpunit
The terminal process "/usr/bin/zsh '-c', '/home/ . . . /vendor/bin/phpunit /home/ . . . /Tests/Feature/ . . . /ControllerIndexTest.php --filter '^.*::it_fails_to_access_the_endpoint_if_the_user_is_not_authenticated( .*)?$' '" terminated with exit code: 1.
```

Anyone has any ideia why this is happening?

**Comment by danilopolani** [comment]
Ehy @joelpiccoli !
I'm gonna archive this because I can't mantain it anymore, I suggest you to try https://github.com/calebporzio/better-phpunit instead by the great Caleb Porzio. This project was a fork of Better PHPUnit and he added in the meanwhile a lot of new features, give it a shot :)
