### ISSUE TITLE
Use the integrated terminal for the tasks

### ISSUE THREAD

**Issue by rakk7** [danilopolani/vscode-yet-another-phpunit#2]
OS: windows 10.

When running the test task, It doesn't get executed in the integrated terminal ( for my case "git bash" ), but instead the default windows's terminal ( CMD ) is opened for the task to execute, not the integrated terminal.

It seems that the default windows's terminal has a higher priority than the integrated terminal.

```json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
```

Thank you,

**Comment by rakk7** [comment]
Alright,

I think I made a mistake, it seems that the tasks do run fine inside the integrated terminal.
The reason I thought it was the default windows's terminal ( CMD ) is the one running the tasks, is because there was no coloring.

So, the issue is the coloring doesn't show up, and I don't know why!. I am going to do some search about this issue, and will put my findings here.

Sorry for wasting your time on this.
Feel free to close this.

**Comment by danilopolani** [comment]
Ehy @rakk7 , don't worry, also I was trying to find a solution for custom shell but it was a bit of a mess. Have you enabled coloring in your `phpunit.xml`? For example:

```
<phpunit
    bootstrap="vendor/autoload.php"
    colors="true"
>
```

**Comment by rakk7** [comment]
Yeah I did, it seems that the issue is related to Windows somehow. ( of course it is )

**Comment by danilopolani** [comment]
What if you try to run the PHPUnit command directly in a terminal of VSCode? You'll get the full command when you run a test:

<img width="1041" alt="Screenshot 2019-05-01 at 15 24 31" src="https://user-images.githubusercontent.com/6277291/57018904-59effa80-6c25-11e9-908f-807dc3e866c7.png">

**Comment by rakk7** [comment]
yeah tried that before, when running the code directly inside VSCode ( bash terminal ):

![2019-05-01 170151](https://user-images.githubusercontent.com/46261343/57021652-81e75a00-6c35-11e9-89ac-912d5d5d82ff.png)

But, when I run the same line outside of VSCode ( bash terminal ) :

![2019-05-01 171816](https://user-images.githubusercontent.com/46261343/57021531-2cab4880-6c35-11e9-8c79-195c20955dfc.png)

**Comment by danilopolani** [comment]
Oh well, then it's a VSCode issue, try to take a look here to configure colors for Git Bash on VSCode: https://stackoverflow.com/a/49059683/1973205

**Comment by rakk7** [comment]
Thank you, I am going to try that.

**Comment by rakk7** [comment]
Thanks for the link, that solved the issue: by adding `--color=always  | cat` at the very end of the command line.

![2019-05-01 170151](https://user-images.githubusercontent.com/46261343/57025281-64b78900-6c3f-11e9-8086-acb006b1d8aa.png)

Is there is a global configuration variable that I can use, to add `--color=always  | cat` at the very end of the command line? because `--color=always  | cat` doesn't work If I put it in `yet-phpunit.ssh.options`  or `yet-phpunit.commandSuffix`

**Comment by danilopolani** [comment]
Currently there isn't, I think I'll add a `shellSuffix` parameter in the new few days. I'll update you as soon as is implemented :)

**Comment by danilopolani** [comment]
@rakk7 I pushed an update on Marketplace with a new `yet-phpunit.ssh.shellAppend` option. I prefer to keep it different from `commandSuffix` because on SSH you may prefer to add different stuff.

Please let me know if this solves :)

**Comment by rakk7** [comment]
@danilopolani Yes, this solved it. 

Note: MS VSCode team has released [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) which solves all the problems I faced with SSH. So, since I am using `Remote Development` plugin, I don't need to configure any SSH options in `vscode-yet-another-phpunit`. Read more here: https://code.visualstudio.com/docs/remote/ssh#_getting-started.

**Comment by danilopolani** [comment]
> @danilopolani Yes, this solved it.
> 
> Note: MS VSCode team has released [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) which solves all the problems I faced with SSH. So, since I am using `Remote Development` plugin, I don't need to configure any SSH options in `vscode-yet-another-phpunit`. Read more here: https://code.visualstudio.com/docs/remote/ssh#_getting-started.

Oh that's cool, didn't know they already release it (in preview tho). I think I'll add a note about this in the README, thank you for your support
