### ISSUE TITLE
CodeLens and functions that are not tests.

### ISSUE THREAD

**Issue by pardmeister** [danilopolani/vscode-yet-another-phpunit#4]
Hi

Codelens does not seem to work if your first functions aren't tests. For example, I always have my setup methods and data providers at the top of my tests, then the test functions under that.  The test link disappears when that is the case. See the images attached.

Image 1, with setUp function.

![Screenshot 2019-05-08 at 09 54 27](https://user-images.githubusercontent.com/6696083/57359225-7802b100-7177-11e9-8fa7-22b93285ab94.png)

Image 2, without setUp function.

![Screenshot 2019-05-08 at 09 54 51](https://user-images.githubusercontent.com/6696083/57359328-be581000-7177-11e9-93a5-a37ee0992e4f.png)

Also, this seems to happen the test functions that come after a non test function.

**Comment by danilopolani** [comment]
Hello,
thank you for the issue - I'll take a look asap.

When I've written the package, I had to write a patch for an issue of `php-parser` (https://github.com/glayzzle/php-parser/issues/250), the engine to fetch methods etc. With that bug, PHPdoc/Docblocks were not retrieved correctly and that may cause the problem. I'll update here as soon as I know something.

**Comment by danilopolani** [comment]
Hello @pardmeister, I pushed a patch for this on the Marketplace, please update the extension and let me know.

Thank you :)

**Comment by pardmeister** [comment]
Hi @danilopolani, it seems fixed in version 1.1.1. Thanks for the quick response :)
