### ISSUE TITLE
phpunit.xml file is required

### ISSUE THREAD

**Issue by AshleyMinshall** [danilopolani/vscode-yet-another-phpunit#9]
The phpunit.xml file is required for the links above classes and tests to work. I just copied the [phpunit.xml](https://raw.githubusercontent.com/laravel/laravel/master/phpunit.xml) here and it worked.

Just putting this here in case the shortcuts weren't working for you.

**Comment by danilopolani** [comment]
Thank you! The package provides an option to let the user select a custom `phpunit.xml` path but I forgot to put it in the README (`xmlConfigFilepath`, https://github.com/danilopolani/vscode-yet-another-phpunit/blob/master/src/commands/phpunit.ts#L74)

I'll put in the README with the alert that a valid `phpunit.xml` is required. Thank you again!
